name: flutter_androssy_kits
description: "Collection of androssy_widgets with advanced styling and customization."
version: 1.0.12
repository: https://github.com/Mohiuddin655-PUB/flutter_androssy_kits

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0